<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'AppChannel' => 'APP',
    'EmailChannel' => '邮件',
    'Id' => '',
    'ScreenChannel' => '站内',
    'SmsChannel' => '短信',
    'Action' => '操作',
    'Category' => '类别',
    'Created At' => '创建时间',
    'Message' => '消息',
    'Route' => '路由',
    'Status' => '状态',
    'Updated At' => '更新时间',
    'User Id' => '用户ID',
];
