<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Id' => '',
    'Message' => '',
    'Route' => '',
    'Seen' => '',
    'User Id' => '',
    'Action' => '操作',
    'All marked as read' => '全部标记为已读',
    'All notifications have been deleted.' => '所有通知已被删除。',
    'All notifications have been marked as read.' => '所有通知已被标记为已读。',
    'AppChannel' => 'App',
    'Category' => '类别',
    'Created At' => '时间',
    'EmailChannel' => '邮件',
    'Enable App Push' => '启用App推送',
    'Enable Email Push' => '启用邮件推送',
    'Enable Sms Push' => '启用短信推送',
    'Manage Notification' => '通知管理',
    'Mark all as read' => '全部标记为已读',
    'Mark as read' => '标记为已读',
    'Notifications' => '通知提醒',
    'Read' => '已读',
    'ScreenChannel' => '站内',
    'Settings' => '设置',
    'SmsChannel' => '短信',
    'Status' => '状态',
    'There are no notifications to show' => '没有通知。',
    'Updated At' => '更新时间',
    'View all' => '查看所有',
];
