<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'All marked as read' => '全部标记为已读',
    'Notice' => '通知提醒',
    'Notifications' => '通知提醒',
    'accepted your answer' => '采纳了你的答案',
    'answered the question' => '回答了问题',
    'commented on the question' => '评论了问题',
    'follow on you' => '关注了你',
    'in your answer' => '',
    'in your comment' => '',
    'invited you to answer' => '邀请你回答',
    'is concerned about the problem' => '关注了问题',
    'mentions you' => '',
    'Successful operation.' => '操作成功',
];
